// Copyright © 2020-2022 The Trustix Authors
//
// SPDX-License-Identifier: GPL-3.0-only

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package dbcache

import ()

type Diffoscope struct {
	Key  string
	Html []byte
}
