trustix: bash -c "cd packages/trustix && nix-shell --run hivemind"
trustix-nix: bash -c "./tools/wait_for_file $TRUSTIX_RPC && cd packages/trustix-nix && nix-shell --run hivemind"
trustix-nix-reprod: bash -c "./tools/wait_for_file $TRUSTIX_RPC && cd packages/trustix-nix-reprod && nix-shell --run hivemind"
trustix-proto: bash -c "cd packages/trustix-proto && nix-shell --run hivemind"
nix-nar-unpack: bash -c "cd packages/nix-nar-unpack && nix-shell --run hivemind"
