trustix: bash -c "cd packages/trustix && hivemind"
trustix-nix: bash -c "./tools/wait_for_file $TRUSTIX_RPC && cd packages/trustix-nix && hivemind"
trustix-nix-r13y: bash -c "cd packages/trustix-nix-r13y && hivemind"
trustix-nix-r13y-web: bash -c "cd packages/trustix-nix-r13y-web && hivemind"
trustix-proto: bash -c "cd packages/trustix-proto && hivemind"
trustix-doc: bash -c "cd packages/trustix-doc && hivemind"
