// Copyright © 2020-2022 The Trustix Authors
//
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc/rpc.proto

package rpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/nix-community/trustix/packages/trustix-proto/api"
	rpc "github.com/nix-community/trustix/packages/trustix-proto/rpc"
	schema "github.com/nix-community/trustix/packages/trustix-proto/schema"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// RPCApiName is the fully-qualified name of the RPCApi service.
	RPCApiName = "trustix_rpc.v1.RPCApi"
	// LogRPCName is the fully-qualified name of the LogRPC service.
	LogRPCName = "trustix_rpc.v1.LogRPC"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RPCApiLogsProcedure is the fully-qualified name of the RPCApi's Logs RPC.
	RPCApiLogsProcedure = "/trustix_rpc.v1.RPCApi/Logs"
	// RPCApiDecideProcedure is the fully-qualified name of the RPCApi's Decide RPC.
	RPCApiDecideProcedure = "/trustix_rpc.v1.RPCApi/Decide"
	// RPCApiGetValueProcedure is the fully-qualified name of the RPCApi's GetValue RPC.
	RPCApiGetValueProcedure = "/trustix_rpc.v1.RPCApi/GetValue"
	// LogRPCGetHeadProcedure is the fully-qualified name of the LogRPC's GetHead RPC.
	LogRPCGetHeadProcedure = "/trustix_rpc.v1.LogRPC/GetHead"
	// LogRPCGetLogEntriesProcedure is the fully-qualified name of the LogRPC's GetLogEntries RPC.
	LogRPCGetLogEntriesProcedure = "/trustix_rpc.v1.LogRPC/GetLogEntries"
	// LogRPCSubmitProcedure is the fully-qualified name of the LogRPC's Submit RPC.
	LogRPCSubmitProcedure = "/trustix_rpc.v1.LogRPC/Submit"
	// LogRPCFlushProcedure is the fully-qualified name of the LogRPC's Flush RPC.
	LogRPCFlushProcedure = "/trustix_rpc.v1.LogRPC/Flush"
)

// RPCApiClient is a client for the trustix_rpc.v1.RPCApi service.
type RPCApiClient interface {
	// Get a list of all logs published/subscribed by this node
	Logs(context.Context, *connect.Request[api.LogsRequest]) (*connect.Response[api.LogsResponse], error)
	// Decide on an output for key based on the configured decision method
	Decide(context.Context, *connect.Request[rpc.DecideRequest]) (*connect.Response[rpc.DecisionResponse], error)
	// Get values by their content-address
	GetValue(context.Context, *connect.Request[api.ValueRequest]) (*connect.Response[api.ValueResponse], error)
}

// NewRPCApiClient constructs a client for the trustix_rpc.v1.RPCApi service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRPCApiClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RPCApiClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &rPCApiClient{
		logs: connect.NewClient[api.LogsRequest, api.LogsResponse](
			httpClient,
			baseURL+RPCApiLogsProcedure,
			opts...,
		),
		decide: connect.NewClient[rpc.DecideRequest, rpc.DecisionResponse](
			httpClient,
			baseURL+RPCApiDecideProcedure,
			opts...,
		),
		getValue: connect.NewClient[api.ValueRequest, api.ValueResponse](
			httpClient,
			baseURL+RPCApiGetValueProcedure,
			opts...,
		),
	}
}

// rPCApiClient implements RPCApiClient.
type rPCApiClient struct {
	logs     *connect.Client[api.LogsRequest, api.LogsResponse]
	decide   *connect.Client[rpc.DecideRequest, rpc.DecisionResponse]
	getValue *connect.Client[api.ValueRequest, api.ValueResponse]
}

// Logs calls trustix_rpc.v1.RPCApi.Logs.
func (c *rPCApiClient) Logs(ctx context.Context, req *connect.Request[api.LogsRequest]) (*connect.Response[api.LogsResponse], error) {
	return c.logs.CallUnary(ctx, req)
}

// Decide calls trustix_rpc.v1.RPCApi.Decide.
func (c *rPCApiClient) Decide(ctx context.Context, req *connect.Request[rpc.DecideRequest]) (*connect.Response[rpc.DecisionResponse], error) {
	return c.decide.CallUnary(ctx, req)
}

// GetValue calls trustix_rpc.v1.RPCApi.GetValue.
func (c *rPCApiClient) GetValue(ctx context.Context, req *connect.Request[api.ValueRequest]) (*connect.Response[api.ValueResponse], error) {
	return c.getValue.CallUnary(ctx, req)
}

// RPCApiHandler is an implementation of the trustix_rpc.v1.RPCApi service.
type RPCApiHandler interface {
	// Get a list of all logs published/subscribed by this node
	Logs(context.Context, *connect.Request[api.LogsRequest]) (*connect.Response[api.LogsResponse], error)
	// Decide on an output for key based on the configured decision method
	Decide(context.Context, *connect.Request[rpc.DecideRequest]) (*connect.Response[rpc.DecisionResponse], error)
	// Get values by their content-address
	GetValue(context.Context, *connect.Request[api.ValueRequest]) (*connect.Response[api.ValueResponse], error)
}

// NewRPCApiHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRPCApiHandler(svc RPCApiHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rPCApiLogsHandler := connect.NewUnaryHandler(
		RPCApiLogsProcedure,
		svc.Logs,
		opts...,
	)
	rPCApiDecideHandler := connect.NewUnaryHandler(
		RPCApiDecideProcedure,
		svc.Decide,
		opts...,
	)
	rPCApiGetValueHandler := connect.NewUnaryHandler(
		RPCApiGetValueProcedure,
		svc.GetValue,
		opts...,
	)
	return "/trustix_rpc.v1.RPCApi/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RPCApiLogsProcedure:
			rPCApiLogsHandler.ServeHTTP(w, r)
		case RPCApiDecideProcedure:
			rPCApiDecideHandler.ServeHTTP(w, r)
		case RPCApiGetValueProcedure:
			rPCApiGetValueHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRPCApiHandler returns CodeUnimplemented from all methods.
type UnimplementedRPCApiHandler struct{}

func (UnimplementedRPCApiHandler) Logs(context.Context, *connect.Request[api.LogsRequest]) (*connect.Response[api.LogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trustix_rpc.v1.RPCApi.Logs is not implemented"))
}

func (UnimplementedRPCApiHandler) Decide(context.Context, *connect.Request[rpc.DecideRequest]) (*connect.Response[rpc.DecisionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trustix_rpc.v1.RPCApi.Decide is not implemented"))
}

func (UnimplementedRPCApiHandler) GetValue(context.Context, *connect.Request[api.ValueRequest]) (*connect.Response[api.ValueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trustix_rpc.v1.RPCApi.GetValue is not implemented"))
}

// LogRPCClient is a client for the trustix_rpc.v1.LogRPC service.
type LogRPCClient interface {
	GetHead(context.Context, *connect.Request[api.LogHeadRequest]) (*connect.Response[schema.LogHead], error)
	GetLogEntries(context.Context, *connect.Request[api.GetLogEntriesRequest]) (*connect.Response[api.LogEntriesResponse], error)
	Submit(context.Context, *connect.Request[rpc.SubmitRequest]) (*connect.Response[rpc.SubmitResponse], error)
	Flush(context.Context, *connect.Request[rpc.FlushRequest]) (*connect.Response[rpc.FlushResponse], error)
}

// NewLogRPCClient constructs a client for the trustix_rpc.v1.LogRPC service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLogRPCClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LogRPCClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &logRPCClient{
		getHead: connect.NewClient[api.LogHeadRequest, schema.LogHead](
			httpClient,
			baseURL+LogRPCGetHeadProcedure,
			opts...,
		),
		getLogEntries: connect.NewClient[api.GetLogEntriesRequest, api.LogEntriesResponse](
			httpClient,
			baseURL+LogRPCGetLogEntriesProcedure,
			opts...,
		),
		submit: connect.NewClient[rpc.SubmitRequest, rpc.SubmitResponse](
			httpClient,
			baseURL+LogRPCSubmitProcedure,
			opts...,
		),
		flush: connect.NewClient[rpc.FlushRequest, rpc.FlushResponse](
			httpClient,
			baseURL+LogRPCFlushProcedure,
			opts...,
		),
	}
}

// logRPCClient implements LogRPCClient.
type logRPCClient struct {
	getHead       *connect.Client[api.LogHeadRequest, schema.LogHead]
	getLogEntries *connect.Client[api.GetLogEntriesRequest, api.LogEntriesResponse]
	submit        *connect.Client[rpc.SubmitRequest, rpc.SubmitResponse]
	flush         *connect.Client[rpc.FlushRequest, rpc.FlushResponse]
}

// GetHead calls trustix_rpc.v1.LogRPC.GetHead.
func (c *logRPCClient) GetHead(ctx context.Context, req *connect.Request[api.LogHeadRequest]) (*connect.Response[schema.LogHead], error) {
	return c.getHead.CallUnary(ctx, req)
}

// GetLogEntries calls trustix_rpc.v1.LogRPC.GetLogEntries.
func (c *logRPCClient) GetLogEntries(ctx context.Context, req *connect.Request[api.GetLogEntriesRequest]) (*connect.Response[api.LogEntriesResponse], error) {
	return c.getLogEntries.CallUnary(ctx, req)
}

// Submit calls trustix_rpc.v1.LogRPC.Submit.
func (c *logRPCClient) Submit(ctx context.Context, req *connect.Request[rpc.SubmitRequest]) (*connect.Response[rpc.SubmitResponse], error) {
	return c.submit.CallUnary(ctx, req)
}

// Flush calls trustix_rpc.v1.LogRPC.Flush.
func (c *logRPCClient) Flush(ctx context.Context, req *connect.Request[rpc.FlushRequest]) (*connect.Response[rpc.FlushResponse], error) {
	return c.flush.CallUnary(ctx, req)
}

// LogRPCHandler is an implementation of the trustix_rpc.v1.LogRPC service.
type LogRPCHandler interface {
	GetHead(context.Context, *connect.Request[api.LogHeadRequest]) (*connect.Response[schema.LogHead], error)
	GetLogEntries(context.Context, *connect.Request[api.GetLogEntriesRequest]) (*connect.Response[api.LogEntriesResponse], error)
	Submit(context.Context, *connect.Request[rpc.SubmitRequest]) (*connect.Response[rpc.SubmitResponse], error)
	Flush(context.Context, *connect.Request[rpc.FlushRequest]) (*connect.Response[rpc.FlushResponse], error)
}

// NewLogRPCHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLogRPCHandler(svc LogRPCHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	logRPCGetHeadHandler := connect.NewUnaryHandler(
		LogRPCGetHeadProcedure,
		svc.GetHead,
		opts...,
	)
	logRPCGetLogEntriesHandler := connect.NewUnaryHandler(
		LogRPCGetLogEntriesProcedure,
		svc.GetLogEntries,
		opts...,
	)
	logRPCSubmitHandler := connect.NewUnaryHandler(
		LogRPCSubmitProcedure,
		svc.Submit,
		opts...,
	)
	logRPCFlushHandler := connect.NewUnaryHandler(
		LogRPCFlushProcedure,
		svc.Flush,
		opts...,
	)
	return "/trustix_rpc.v1.LogRPC/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LogRPCGetHeadProcedure:
			logRPCGetHeadHandler.ServeHTTP(w, r)
		case LogRPCGetLogEntriesProcedure:
			logRPCGetLogEntriesHandler.ServeHTTP(w, r)
		case LogRPCSubmitProcedure:
			logRPCSubmitHandler.ServeHTTP(w, r)
		case LogRPCFlushProcedure:
			logRPCFlushHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLogRPCHandler returns CodeUnimplemented from all methods.
type UnimplementedLogRPCHandler struct{}

func (UnimplementedLogRPCHandler) GetHead(context.Context, *connect.Request[api.LogHeadRequest]) (*connect.Response[schema.LogHead], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trustix_rpc.v1.LogRPC.GetHead is not implemented"))
}

func (UnimplementedLogRPCHandler) GetLogEntries(context.Context, *connect.Request[api.GetLogEntriesRequest]) (*connect.Response[api.LogEntriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trustix_rpc.v1.LogRPC.GetLogEntries is not implemented"))
}

func (UnimplementedLogRPCHandler) Submit(context.Context, *connect.Request[rpc.SubmitRequest]) (*connect.Response[rpc.SubmitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trustix_rpc.v1.LogRPC.Submit is not implemented"))
}

func (UnimplementedLogRPCHandler) Flush(context.Context, *connect.Request[rpc.FlushRequest]) (*connect.Response[rpc.FlushResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trustix_rpc.v1.LogRPC.Flush is not implemented"))
}
