#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

while true; do
    if test -f  "$DIR/../.environment"; then
        break
    fi
    echo "Waiting for log..."
    sleep 1
done

export $(grep -v '^#' $DIR/../.environment | xargs)

exec ./trustix --action daemon
