#!/usr/bin/env bash
set -euo pipefail

datadir=$WORKDIR/mysql/datadir
socket=$WORKDIR/mysql.sock

mkdir -p $datadir

cd $WORKDIR/mysql

set -x
mysql_install_db --basedir $MYSQL_BASEDIR --datadir $datadir --socket $socket

exec mysqld --basedir $MYSQL_BASEDIR --datadir $datadir --socket $socket
