#!/usr/bin/env bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export $(grep -v '^#' $DIR/../.environment | xargs)
exec $DIR/../trustix -tlog_endpoint :8090 -tlog_id $LOG_ID
