// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	schema "github.com/tweag/trustix/packages/trustix-proto/schema"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrustixLogAPIClient is the client API for TrustixLogAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrustixLogAPIClient interface {
	GetSTH(ctx context.Context, in *STHRequest, opts ...grpc.CallOption) (*schema.STH, error)
	GetValue(ctx context.Context, in *ValueRequest, opts ...grpc.CallOption) (*ValueResponse, error)
	GetLogConsistencyProof(ctx context.Context, in *GetLogConsistencyProofRequest, opts ...grpc.CallOption) (*ProofResponse, error)
	GetLogAuditProof(ctx context.Context, in *GetLogAuditProofRequest, opts ...grpc.CallOption) (*ProofResponse, error)
	GetLogEntries(ctx context.Context, in *GetLogEntriesRequest, opts ...grpc.CallOption) (*LogEntriesResponse, error)
	GetMapValue(ctx context.Context, in *GetMapValueRequest, opts ...grpc.CallOption) (*MapValueResponse, error)
	GetMHLogConsistencyProof(ctx context.Context, in *GetLogConsistencyProofRequest, opts ...grpc.CallOption) (*ProofResponse, error)
	GetMHLogAuditProof(ctx context.Context, in *GetLogAuditProofRequest, opts ...grpc.CallOption) (*ProofResponse, error)
	GetMHLogEntries(ctx context.Context, in *GetLogEntriesRequest, opts ...grpc.CallOption) (*LogEntriesResponse, error)
}

type trustixLogAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewTrustixLogAPIClient(cc grpc.ClientConnInterface) TrustixLogAPIClient {
	return &trustixLogAPIClient{cc}
}

func (c *trustixLogAPIClient) GetSTH(ctx context.Context, in *STHRequest, opts ...grpc.CallOption) (*schema.STH, error) {
	out := new(schema.STH)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetSTH", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustixLogAPIClient) GetValue(ctx context.Context, in *ValueRequest, opts ...grpc.CallOption) (*ValueResponse, error) {
	out := new(ValueResponse)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustixLogAPIClient) GetLogConsistencyProof(ctx context.Context, in *GetLogConsistencyProofRequest, opts ...grpc.CallOption) (*ProofResponse, error) {
	out := new(ProofResponse)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetLogConsistencyProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustixLogAPIClient) GetLogAuditProof(ctx context.Context, in *GetLogAuditProofRequest, opts ...grpc.CallOption) (*ProofResponse, error) {
	out := new(ProofResponse)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetLogAuditProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustixLogAPIClient) GetLogEntries(ctx context.Context, in *GetLogEntriesRequest, opts ...grpc.CallOption) (*LogEntriesResponse, error) {
	out := new(LogEntriesResponse)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetLogEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustixLogAPIClient) GetMapValue(ctx context.Context, in *GetMapValueRequest, opts ...grpc.CallOption) (*MapValueResponse, error) {
	out := new(MapValueResponse)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetMapValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustixLogAPIClient) GetMHLogConsistencyProof(ctx context.Context, in *GetLogConsistencyProofRequest, opts ...grpc.CallOption) (*ProofResponse, error) {
	out := new(ProofResponse)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetMHLogConsistencyProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustixLogAPIClient) GetMHLogAuditProof(ctx context.Context, in *GetLogAuditProofRequest, opts ...grpc.CallOption) (*ProofResponse, error) {
	out := new(ProofResponse)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetMHLogAuditProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustixLogAPIClient) GetMHLogEntries(ctx context.Context, in *GetLogEntriesRequest, opts ...grpc.CallOption) (*LogEntriesResponse, error) {
	out := new(LogEntriesResponse)
	err := c.cc.Invoke(ctx, "/trustix.TrustixLogAPI/GetMHLogEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrustixLogAPIServer is the server API for TrustixLogAPI service.
// All implementations must embed UnimplementedTrustixLogAPIServer
// for forward compatibility
type TrustixLogAPIServer interface {
	GetSTH(context.Context, *STHRequest) (*schema.STH, error)
	GetValue(context.Context, *ValueRequest) (*ValueResponse, error)
	GetLogConsistencyProof(context.Context, *GetLogConsistencyProofRequest) (*ProofResponse, error)
	GetLogAuditProof(context.Context, *GetLogAuditProofRequest) (*ProofResponse, error)
	GetLogEntries(context.Context, *GetLogEntriesRequest) (*LogEntriesResponse, error)
	GetMapValue(context.Context, *GetMapValueRequest) (*MapValueResponse, error)
	GetMHLogConsistencyProof(context.Context, *GetLogConsistencyProofRequest) (*ProofResponse, error)
	GetMHLogAuditProof(context.Context, *GetLogAuditProofRequest) (*ProofResponse, error)
	GetMHLogEntries(context.Context, *GetLogEntriesRequest) (*LogEntriesResponse, error)
	mustEmbedUnimplementedTrustixLogAPIServer()
}

// UnimplementedTrustixLogAPIServer must be embedded to have forward compatible implementations.
type UnimplementedTrustixLogAPIServer struct {
}

func (UnimplementedTrustixLogAPIServer) GetSTH(context.Context, *STHRequest) (*schema.STH, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSTH not implemented")
}
func (UnimplementedTrustixLogAPIServer) GetValue(context.Context, *ValueRequest) (*ValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedTrustixLogAPIServer) GetLogConsistencyProof(context.Context, *GetLogConsistencyProofRequest) (*ProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogConsistencyProof not implemented")
}
func (UnimplementedTrustixLogAPIServer) GetLogAuditProof(context.Context, *GetLogAuditProofRequest) (*ProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogAuditProof not implemented")
}
func (UnimplementedTrustixLogAPIServer) GetLogEntries(context.Context, *GetLogEntriesRequest) (*LogEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogEntries not implemented")
}
func (UnimplementedTrustixLogAPIServer) GetMapValue(context.Context, *GetMapValueRequest) (*MapValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMapValue not implemented")
}
func (UnimplementedTrustixLogAPIServer) GetMHLogConsistencyProof(context.Context, *GetLogConsistencyProofRequest) (*ProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMHLogConsistencyProof not implemented")
}
func (UnimplementedTrustixLogAPIServer) GetMHLogAuditProof(context.Context, *GetLogAuditProofRequest) (*ProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMHLogAuditProof not implemented")
}
func (UnimplementedTrustixLogAPIServer) GetMHLogEntries(context.Context, *GetLogEntriesRequest) (*LogEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMHLogEntries not implemented")
}
func (UnimplementedTrustixLogAPIServer) mustEmbedUnimplementedTrustixLogAPIServer() {}

// UnsafeTrustixLogAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrustixLogAPIServer will
// result in compilation errors.
type UnsafeTrustixLogAPIServer interface {
	mustEmbedUnimplementedTrustixLogAPIServer()
}

func RegisterTrustixLogAPIServer(s grpc.ServiceRegistrar, srv TrustixLogAPIServer) {
	s.RegisterService(&TrustixLogAPI_ServiceDesc, srv)
}

func _TrustixLogAPI_GetSTH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(STHRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetSTH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetSTH",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetSTH(ctx, req.(*STHRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustixLogAPI_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetValue(ctx, req.(*ValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustixLogAPI_GetLogConsistencyProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogConsistencyProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetLogConsistencyProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetLogConsistencyProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetLogConsistencyProof(ctx, req.(*GetLogConsistencyProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustixLogAPI_GetLogAuditProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogAuditProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetLogAuditProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetLogAuditProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetLogAuditProof(ctx, req.(*GetLogAuditProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustixLogAPI_GetLogEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetLogEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetLogEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetLogEntries(ctx, req.(*GetLogEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustixLogAPI_GetMapValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetMapValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetMapValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetMapValue(ctx, req.(*GetMapValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustixLogAPI_GetMHLogConsistencyProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogConsistencyProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetMHLogConsistencyProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetMHLogConsistencyProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetMHLogConsistencyProof(ctx, req.(*GetLogConsistencyProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustixLogAPI_GetMHLogAuditProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogAuditProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetMHLogAuditProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetMHLogAuditProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetMHLogAuditProof(ctx, req.(*GetLogAuditProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustixLogAPI_GetMHLogEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustixLogAPIServer).GetMHLogEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trustix.TrustixLogAPI/GetMHLogEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustixLogAPIServer).GetMHLogEntries(ctx, req.(*GetLogEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrustixLogAPI_ServiceDesc is the grpc.ServiceDesc for TrustixLogAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrustixLogAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trustix.TrustixLogAPI",
	HandlerType: (*TrustixLogAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSTH",
			Handler:    _TrustixLogAPI_GetSTH_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _TrustixLogAPI_GetValue_Handler,
		},
		{
			MethodName: "GetLogConsistencyProof",
			Handler:    _TrustixLogAPI_GetLogConsistencyProof_Handler,
		},
		{
			MethodName: "GetLogAuditProof",
			Handler:    _TrustixLogAPI_GetLogAuditProof_Handler,
		},
		{
			MethodName: "GetLogEntries",
			Handler:    _TrustixLogAPI_GetLogEntries_Handler,
		},
		{
			MethodName: "GetMapValue",
			Handler:    _TrustixLogAPI_GetMapValue_Handler,
		},
		{
			MethodName: "GetMHLogConsistencyProof",
			Handler:    _TrustixLogAPI_GetMHLogConsistencyProof_Handler,
		},
		{
			MethodName: "GetMHLogAuditProof",
			Handler:    _TrustixLogAPI_GetMHLogAuditProof_Handler,
		},
		{
			MethodName: "GetMHLogEntries",
			Handler:    _TrustixLogAPI_GetMHLogEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
