#!/usr/bin/env bash
set -x
./dev/mysql_wait
mysql --socket $WORKDIR/mysql.sock -D test < $TRILLIAN_SCHEMA
exec trillian_log_signer --storage_system=mysql --mysql_uri "tcp(127.0.0.1:3306)/test" --rpc_endpoint=0.0.0.0:8092 --http_endpoint=0.0.0.0:8093 --alsologtostderr --force_master
