# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/queue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema/queue.proto',
  package='',
  syntax='proto2',
  serialized_options=b'Z\037github.com/tweag/trustix/schema',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12schema/queue.proto\"\'\n\x0bSubmitQueue\x12\x0b\n\x03Min\x18\x01 \x02(\x04\x12\x0b\n\x03Max\x18\x02 \x02(\x04\x42!Z\x1fgithub.com/tweag/trustix/schema'
)




_SUBMITQUEUE = _descriptor.Descriptor(
  name='SubmitQueue',
  full_name='SubmitQueue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Min', full_name='SubmitQueue.Min', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Max', full_name='SubmitQueue.Max', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['SubmitQueue'] = _SUBMITQUEUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitQueue = _reflection.GeneratedProtocolMessageType('SubmitQueue', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITQUEUE,
  '__module__' : 'schema.queue_pb2'
  # @@protoc_insertion_point(class_scope:SubmitQueue)
  })
_sym_db.RegisterMessage(SubmitQueue)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
