// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: trustix.proto

package trustix

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SubmitReply_Status int32

const (
	SubmitReply_OK SubmitReply_Status = 0
)

// Enum value maps for SubmitReply_Status.
var (
	SubmitReply_Status_name = map[int32]string{
		0: "OK",
	}
	SubmitReply_Status_value = map[string]int32{
		"OK": 0,
	}
)

func (x SubmitReply_Status) Enum() *SubmitReply_Status {
	p := new(SubmitReply_Status)
	*p = x
	return p
}

func (x SubmitReply_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmitReply_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_trustix_proto_enumTypes[0].Descriptor()
}

func (SubmitReply_Status) Type() protoreflect.EnumType {
	return &file_trustix_proto_enumTypes[0]
}

func (x SubmitReply_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmitReply_Status.Descriptor instead.
func (SubmitReply_Status) EnumDescriptor() ([]byte, []int) {
	return file_trustix_proto_rawDescGZIP(), []int{1, 0}
}

type SubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputHash  []byte `protobuf:"bytes,1,opt,name=InputHash,proto3" json:"InputHash,omitempty"`
	OutputHash []byte `protobuf:"bytes,2,opt,name=OutputHash,proto3" json:"OutputHash,omitempty"`
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trustix_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trustix_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_trustix_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetInputHash() []byte {
	if x != nil {
		return x.InputHash
	}
	return nil
}

func (x *SubmitRequest) GetOutputHash() []byte {
	if x != nil {
		return x.OutputHash
	}
	return nil
}

type SubmitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SubmitReply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=trustix.SubmitReply_Status" json:"status,omitempty"`
}

func (x *SubmitReply) Reset() {
	*x = SubmitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trustix_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReply) ProtoMessage() {}

func (x *SubmitReply) ProtoReflect() protoreflect.Message {
	mi := &file_trustix_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReply.ProtoReflect.Descriptor instead.
func (*SubmitReply) Descriptor() ([]byte, []int) {
	return file_trustix_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitReply) GetStatus() SubmitReply_Status {
	if x != nil {
		return x.Status
	}
	return SubmitReply_OK
}

var File_trustix_proto protoreflect.FileDescriptor

var file_trustix_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x74, 0x72, 0x75, 0x73, 0x74, 0x69, 0x78, 0x22, 0x4d, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68, 0x22, 0x54, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x69, 0x78,
	0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x10, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x32, 0x4a, 0x0a,
	0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x74, 0x72, 0x75, 0x73,
	0x74, 0x69, 0x78, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x69, 0x78, 0x2e, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x65, 0x61, 0x67, 0x2f, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x69, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trustix_proto_rawDescOnce sync.Once
	file_trustix_proto_rawDescData = file_trustix_proto_rawDesc
)

func file_trustix_proto_rawDescGZIP() []byte {
	file_trustix_proto_rawDescOnce.Do(func() {
		file_trustix_proto_rawDescData = protoimpl.X.CompressGZIP(file_trustix_proto_rawDescData)
	})
	return file_trustix_proto_rawDescData
}

var file_trustix_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trustix_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trustix_proto_goTypes = []interface{}{
	(SubmitReply_Status)(0), // 0: trustix.SubmitReply.Status
	(*SubmitRequest)(nil),   // 1: trustix.SubmitRequest
	(*SubmitReply)(nil),     // 2: trustix.SubmitReply
}
var file_trustix_proto_depIdxs = []int32{
	0, // 0: trustix.SubmitReply.status:type_name -> trustix.SubmitReply.Status
	1, // 1: trustix.Greeter.SubmitMapping:input_type -> trustix.SubmitRequest
	2, // 2: trustix.Greeter.SubmitMapping:output_type -> trustix.SubmitReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trustix_proto_init() }
func file_trustix_proto_init() {
	if File_trustix_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trustix_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trustix_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trustix_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trustix_proto_goTypes,
		DependencyIndexes: file_trustix_proto_depIdxs,
		EnumInfos:         file_trustix_proto_enumTypes,
		MessageInfos:      file_trustix_proto_msgTypes,
	}.Build()
	File_trustix_proto = out.File
	file_trustix_proto_rawDesc = nil
	file_trustix_proto_goTypes = nil
	file_trustix_proto_depIdxs = nil
}
