on: push
name: tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install staticcheck
      run: pwd && cd .. && go get -v -u honnef.co/go/tools/cmd/staticcheck && cd -
      shell: bash
    - name: Install golint
      run: pwd && cd .. && go get -v -u golang.org/x/lint/golint && cd -
      shell: bash
    - name: Update PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Fmt
      if: matrix.platform != 'windows-latest' # :(
      run: "F=$(gofmt -l .) ; if [[ $F ]] ; then echo $F ; exit 1 ; fi"
      shell: bash
    - name: Vet
      run: go vet ./...
    - name: Staticcheck
      run: staticcheck ./...
    - name: Lint
      run: golint ./...
    - name: Test
      run: go test -race ./...
