#!/usr/bin/env python
from lib import exec_cmd, wait_for_db


if __name__ == "__main__":
    wait_for_db()
    exec_cmd(
        [
            "uvicorn",
            "--debug",
            "--reload-dir",
            "trustix_api",
            "--reload-dir",
            "trustix_nix_reprod",
            "--reload-dir",
            "trustix_proto",
            "--reload-dir",
            "trustix_schema",
            "trustix_nix_reprod.app:app",
        ],
    )
