// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: mapentry.proto

package schema

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MapEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Digest []byte  `protobuf:"bytes,1,req,name=Digest" json:"Digest,omitempty"`
	Index  *uint64 `protobuf:"varint,2,req,name=Index" json:"Index,omitempty"`
}

func (x *MapEntry) Reset() {
	*x = MapEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapentry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEntry) ProtoMessage() {}

func (x *MapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mapentry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEntry.ProtoReflect.Descriptor instead.
func (*MapEntry) Descriptor() ([]byte, []int) {
	return file_mapentry_proto_rawDescGZIP(), []int{0}
}

func (x *MapEntry) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *MapEntry) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

var File_mapentry_proto protoreflect.FileDescriptor

var file_mapentry_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x70, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x38, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x06, 0x44, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x04, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x65, 0x61, 0x67, 0x2f, 0x74,
	0x72, 0x75, 0x73, 0x74, 0x69, 0x78, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
}

var (
	file_mapentry_proto_rawDescOnce sync.Once
	file_mapentry_proto_rawDescData = file_mapentry_proto_rawDesc
)

func file_mapentry_proto_rawDescGZIP() []byte {
	file_mapentry_proto_rawDescOnce.Do(func() {
		file_mapentry_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapentry_proto_rawDescData)
	})
	return file_mapentry_proto_rawDescData
}

var file_mapentry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mapentry_proto_goTypes = []interface{}{
	(*MapEntry)(nil), // 0: MapEntry
}
var file_mapentry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mapentry_proto_init() }
func file_mapentry_proto_init() {
	if File_mapentry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapentry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapentry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapentry_proto_goTypes,
		DependencyIndexes: file_mapentry_proto_depIdxs,
		MessageInfos:      file_mapentry_proto_msgTypes,
	}.Build()
	File_mapentry_proto = out.File
	file_mapentry_proto_rawDesc = nil
	file_mapentry_proto_goTypes = nil
	file_mapentry_proto_depIdxs = nil
}
