// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Derivation struct {
	ID     int64
	Drv    string
	System string
}

type Evaluation struct {
	ID        int64
	CommitSha string
	Timestamp time.Time
}
