#!/usr/bin/env python
import subprocess
import os.path
import time
import os


if __name__ == "__main__":
    sockets_dir = os.path.join(os.environ["TMPDIR"], "nix-trustix-dash-psql-sockets")
    socket = os.path.join(sockets_dir, ".s.PGSQL.5432")
    while not os.path.exists(sockets_dir):
        time.sleep(0.1)

    time.sleep(1)
    subprocess.run(["createdb", "nix-trustix-dash", "-h", sockets_dir])

    while True:
        time.sleep(1000)
