#!/usr/bin/env python
import subprocess
from lib import (
    PSQL_SOCKETS_DIR,
    PSQL_DB_NAME,
    wait_for_psql,
    db_exists,
    exec_cmd,
)


if __name__ == "__main__":
    wait_for_psql()

    if not db_exists():
        subprocess.run(["createdb", PSQL_DB_NAME, "-h", PSQL_SOCKETS_DIR])

    exec_cmd(["sleep", "infinity"])
