#!/usr/bin/env python
from lib import (
    watch_recursive,
    wait_for_db,
    ROOT_DIR,
    run_cmd,
)
import os.path


if __name__ == "__main__":
    wait_for_db()

    def callback():
        run_cmd(["aerich", "upgrade"])

    callback()  # Run at least once on startup

    watch_recursive(
        [os.path.join(ROOT_DIR, "migrations")],
        callback,
        delay=2,
    )
