#!/usr/bin/env python
import subprocess
import os.path
import os

from lib import (
    PSQL_SOCKETS_DIR,
    PSQL_DATA_DIR,
    ensure_dir,
    exec_cmd,
)


if __name__ == "__main__":

    ensure_dir(PSQL_SOCKETS_DIR)

    if not os.path.exists(PSQL_DATA_DIR):
        subprocess.check_output(["initdb", PSQL_DATA_DIR])
        with open(os.path.join(PSQL_DATA_DIR, "postgresql.conf"), "a") as f:
            f.write("\n# Trustix options\n")
            f.write(f"unix_socket_directories = '{PSQL_SOCKETS_DIR}'\n")

    exec_cmd(["postgres", "-D", PSQL_DATA_DIR])
