#!/usr/bin/env bash

# Copyright © 2020-2022 The Trustix Authors
#
# SPDX-License-Identifier: MIT

set -euo pipefail

find . -name go.mod | while read mod; do
    dir=$(dirname $mod)

    cd $dir
    go get -u ./... && go mod tidy && gomod2nix
    cd -
done
