#!/usr/bin/env bash

# Copyright © 2020-2022 The Trustix Authors
#
# SPDX-License-Identifier: MIT

set -euo pipefail

file=$(echo "$1" | sed s/'unix:\/\/'/''/)

while true; do
    if test -e "$file"; then
        break
    fi
    sleep 0.2
done
