#!/usr/bin/env python
import subprocess
import os.path
from typing import (
    List,
)


PY_SHEBANGS: List[str] = [
    "#!/usr/bin/env python",
    "#!/usr/bin/env python3",
]


if __name__ == "__main__":
    # List files using git (we don't want to read state files and such for checks)
    p = subprocess.run(["git", "ls-files"], stdout=subprocess.PIPE, check=True)

    # List all files and skip any empty strings when splitting
    git_files: List[str] = [f for f in p.stdout.decode().split("\n") if f]

    # Filtered list of all Python files in the repo
    py_files: List[str] = []

    for f in git_files:
        _, ext = os.path.splitext(f)

        # File extension match
        if ext == ".py":
            py_files.append(f)
            continue

        # Shebang match
        with open(f) as fd:
            try:
                opening_line = fd.readline().strip()
            except UnicodeDecodeError:
                continue

            if opening_line in PY_SHEBANGS:
                py_files.append(f)
                continue

    if not py_files:
        exit(0)

    subprocess.run(["black", "--check"] + py_files, check=True)
