#!/usr/bin/env bash

# Copyright © 2020-2022 The Trustix Authors
#
# SPDX-License-Identifier: MIT

set -euo pipefail

args="./... --out-format github-actions"

ls ./packages/*/go.mod | xargs dirname | while read pkgdir; do
    echo "Checking $pkgdir"
    nix-shell "$pkgdir/shell.nix" --run "cd $pkgdir && golangci-lint run --timeout 15m0s $args"
done
