schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v1.3.2"
    hash = "sha256-FIwyH67KryRWI9Bk4R8s1zFP0IgKR4L66wNQJYQZLeg="
  [mod."github.com/ClickHouse/clickhouse-go"]
    version = "v1.5.4"
    hash = "sha256-De5oreE/B/y5fjlFzxDafjr7wGjnAPPooqOFTGtuSoA="
  [mod."github.com/adrg/xdg"]
    version = "v0.4.0"
    hash = "sha256-zGjkdUQmrVqD6rMO9oDY+TeJCpuqnHyvkPCaXDlac/U="
  [mod."github.com/antlr/antlr4/runtime/Go/antlr"]
    version = "v1.4.10"
    hash = "sha256-QZn1eltqxkZYvf7g/GQv6HftH+OuKJTVjIjyyHZw9jI="
  [mod."github.com/antlr/antlr4/runtime/Go/antlr/v4"]
    version = "v4.0.0-20230321174746-8dcc6526cfb1"
    hash = "sha256-kuqZ7vX7JsfGd+VxOK6lb0iVpq62XjKVguTkiPS8QvE="
  [mod."github.com/bakins/logrus-middleware"]
    version = "v0.0.0-20180426214643-ce4c6f8deb07"
    hash = "sha256-8BaMIVqeDOfbM+PN6IyHHsu3pOUO/hqrGT/+HaECZjo="
  [mod."github.com/benbjohnson/clock"]
    version = "v1.3.5"
    hash = "sha256-pSTHNILoQpLL64bvdcNwXv+dVJ3LBZRoECpj7m8C9tw="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bufbuild/connect-go"]
    version = "v1.10.0"
    hash = "sha256-cc3eAfPEOiXFsa14aO4ui8GqUy+mzkRGIVeW31yYQRI="
  [mod."github.com/buger/jsonparser"]
    version = "v1.1.1"
    hash = "sha256-T6dXT6Vzpm8gvQYi+c2LZkV+8ZOp0ZXBX7+e1mlliZE="
  [mod."github.com/bytecodealliance/wasmtime-go"]
    version = "v1.0.0"
    hash = "sha256-Pd7O58M+NdANd4nOyaGM7gqC4KO45SZpxmjM2/MB9dU="
  [mod."github.com/bytecodealliance/wasmtime-go/v8"]
    version = "v8.0.0"
    hash = "sha256-HhB0pUd5VXwZ0eVPr2jeecHt/7cU6V/y6uhKHmpZkrg="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/cloudflare/golz4"]
    version = "v0.0.0-20150217214814-ef862a3cdc58"
    hash = "sha256-we6f7JwDfq9PQ+w9ey8yBwELnBhtmzht0yAApcblcTI="
  [mod."github.com/coreos/go-systemd"]
    version = "v0.0.0-20191104093116-d3cd4ed1dbcf"
    hash = "sha256-HEnyJ9uxZdlZb2lG8YwxYuuYTCW8PpxUhADqEwNlN5U="
  [mod."github.com/cubicdaiya/gonp"]
    version = "v1.0.4"
    hash = "sha256-EzI6qi2dYF/aCSNXe1zhoA24gaj6AFjHPwBbD2v7L64="
  [mod."github.com/cznic/mathutil"]
    version = "v0.0.0-20181122101859-297441e03548"
    hash = "sha256-PdMEn2mI6RASqkG7G8wsvjpRsEoHpSWWXG/iwC8KeaM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/denisenkom/go-mssqldb"]
    version = "v0.12.3"
    hash = "sha256-iniC1Zul2U/hiH5EuOEch+idjwifoHw7MMeeGJq9DT4="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.7.1"
    hash = "sha256-3iKt+BKDz5FX2246Tg41weIuEDYd1YI40N6alJI9Bks="
  [mod."github.com/golang-sql/civil"]
    version = "v0.0.0-20220223132316-b832511892a9"
    hash = "sha256-IEz9BkkHyFfs9R4aMxH/c/tD510qSyFEaKrpO4arWpQ="
  [mod."github.com/golang-sql/sqlexp"]
    version = "v0.1.0"
    hash = "sha256-FhKWdt7vwzTbIsx2u+AzrKO1VFxTw/lbgD9/V5G76jw="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/cel-go"]
    version = "v0.18.1"
    hash = "sha256-siipnL6YAQOIzdoik2z4MvgPeOHpxgX+8EHUtY3b5yo="
  [mod."github.com/hashicorp/go-uuid"]
    version = "v1.0.3"
    hash = "sha256-8893qBbaug2yhxElowSrl3PrfhYlQ7cZ71QBgZWqpHE="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v1.0.2"
    hash = "sha256-yy+5botc6T5wXgOe2mfNXJP3wr+MkVlUZ2JBkmmrA48="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20221227161230-091c0ba34f0a"
    hash = "sha256-rBtUw15WPPDp2eulHXH5e2zCIed1OPFYwlCpgDOnGRM="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.4.3"
    hash = "sha256-ngF3yz6LQOwZUX5RgGqSJs4TUaabu64p3OF3h/d50hA="
  [mod."github.com/jinzhu/inflection"]
    version = "v1.0.0"
    hash = "sha256-3h3pHib5MaCXKyKLIMyQnSptDJ16kPjCOQPoEBoQsZg="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.5"
    hash = "sha256-/M8CHNah2/EPr0va44r1Sx+3H6E+jN8bGFi5jQkLBrM="
  [mod."github.com/kyleconroy/sqlc"]
    version = "v1.19.1"
    hash = "sha256-/yT0MlJMY1pXl66rlul8oOJrzv1SEinQQy0SOKCyJqc="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.17"
    hash = "sha256-ictf2uCW2AnQbykhI0kKPXwzHQlbHHZflZgvpqGFquY="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/matttproud/golang_protobuf_extensions/v2"]
    version = "v2.0.0"
    hash = "sha256-gcAN8jKL0ve8pcgDkxr2Lc8CUBG39ri9QAp0zrzchEs="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.1"
    hash = "sha256-4hfGDIQaWq8fvtGzHDhoK9v2IocXnJY7OAL6saMJbmA="
  [mod."github.com/mr-tron/base58"]
    version = "v1.2.0"
    hash = "sha256-8FzMu3kHUbBX10pUdtGf59Ag7BNupx8ZHeUaodR1/Vk="
  [mod."github.com/multiformats/go-multihash"]
    version = "v0.2.3"
    hash = "sha256-zqIIE5jMFzm+qhUrouSF+WdXGeHUEYIQvVnKWWU6mRs="
  [mod."github.com/multiformats/go-varint"]
    version = "v0.0.7"
    hash = "sha256-To3Uuv7uSUJEr5OTwxE1LEIpA62xY3M/KKMNlscHmlA="
  [mod."github.com/nix-community/go-nix"]
    version = "v0.0.0-20231012070617-9b176785e54d"
    hash = "sha256-CuGARFZPJw8JrBnTIuDLSaQKKbcuVnnkhAamwEohOHk="
  [mod."github.com/pbnjay/memory"]
    version = "v0.0.0-20210728143218-7b4eea64cf58"
    hash = "sha256-QI+F1oPLOOtwNp8+m45OOoSfYFs3QVjGzE0rFdpF/IA="
  [mod."github.com/pganalyze/pg_query_go/v2"]
    version = "v2.2.0"
    hash = "sha256-Yv6YLVQ8hgPtiPaDiROmzpGzPSY0Q58dPgqY290Yf0k="
  [mod."github.com/pganalyze/pg_query_go/v4"]
    version = "v4.2.3"
    hash = "sha256-nAnEaVZU4N8bfTKhQZfYfz/1uGRc4v3Bi+0X3CxMZ5c="
  [mod."github.com/pingcap/errors"]
    version = "v0.11.5-0.20210425183316-da1aaba5fb63"
    hash = "sha256-DMCuYkR93VHzoR7UC4WhUGp4XGaEub4O0jAf+hAvljQ="
  [mod."github.com/pingcap/failpoint"]
    version = "v0.0.0-20220801062533-2eaa32854a6c"
    hash = "sha256-jWq64FsR+5BH4jEc71EWfFIXGoNSwtO4LRbof70H89o="
  [mod."github.com/pingcap/log"]
    version = "v1.1.0"
    hash = "sha256-JT33CJMknTXha1ERt4s6vV9fyx99J+Ot8rFrNKXTsTc="
  [mod."github.com/pingcap/tidb/parser"]
    version = "v0.0.0-20231013125129-93a834a6bf8d"
    hash = "sha256-55AltUlRJZUDlysK/4JiPH8Ct90oXGUDsgF8WV4V4ts="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pressly/goose"]
    version = "v2.7.0+incompatible"
    hash = "sha256-tIoIYGqFIkGxaVG0NM4DelK+iedlB8jgtEqWJiN+7K4="
  [mod."github.com/pressly/goose/v3"]
    version = "v3.15.1"
    hash = "sha256-rUB/Amw37w/sGopfEU/JeWidx9IpS81iXQ5Lk46EJRI="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.17.0"
    hash = "sha256-FIIzCuNqHdVzpbyH7yAp7Tcu+1tPxEMS5g6KfsGQBGE="
  [mod."github.com/prometheus/client_model"]
    version = "v0.5.0"
    hash = "sha256-/sXlngf8AoEIeLIiaLg6Y7uYPVq7tI0qnLt0mUyKid4="
  [mod."github.com/prometheus/common"]
    version = "v0.45.0"
    hash = "sha256-N7CDcekAW8InquaVHHkuZ6gNCoW8J0yDlH5A+dj3cfE="
  [mod."github.com/prometheus/procfs"]
    version = "v0.12.0"
    hash = "sha256-Y4ZZmxIpVCO67zN3pGwSk2TcI88zvmGJkgwq9DRTwFw="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/riza-io/grpc-go"]
    version = "v0.2.0"
    hash = "sha256-toqQdnwlcKbJHl1mv9cDBwRfyXAMBwbfun+yC9+Rwgw="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/spaolacci/murmur3"]
    version = "v1.1.0"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/spf13/cobra"]
    version = "v1.7.0"
    hash = "sha256-bom9Zpnz8XPwx9IVF+GAodd3NVQ1dM1Uwxn8sy4Gmzs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.3.0"
    hash = "sha256-X0ilcefeqVQ44B9WT6euCMcigs7oLFypOQaGI33kGr8="
  [mod."github.com/ziutek/mymysql"]
    version = "v1.5.4"
    hash = "sha256-kOAoAGINbmby8UhfxVvZPQ4tRQd92Tp96HyAPLE0cts="
  [mod."go.uber.org/atomic"]
    version = "v1.11.0"
    hash = "sha256-TyYws/cSPVqYNffFX0gbDml1bD4bBGcysrUWU7mHPIY="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.26.0"
    hash = "sha256-EUQnALSDtoJryWp01K/PMbRUvQYG1uDbqGnlJ/7thE4="
  [mod."golang.org/x/crypto"]
    version = "v0.14.0"
    hash = "sha256-UUSt3X/i34r1K0mU+Y5IzljX5HYy07JcHh39Pm1MU+o="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20231006140011-7918f672742d"
    hash = "sha256-2SO1etTQ6UCUhADR5sgvDEDLHcj77pJKCIa/8mGDbAo="
  [mod."golang.org/x/net"]
    version = "v0.17.0"
    hash = "sha256-qRawHWLSsJ06QNbLhUWPXGVSO1eaioeC9xZlUEWN8J8="
  [mod."golang.org/x/sync"]
    version = "v0.4.0"
    hash = "sha256-VCl5IerUva6XZqGXHa0J/r/ewsbOIIP7EBqyh1JGsXY="
  [mod."golang.org/x/sys"]
    version = "v0.13.0"
    hash = "sha256-/+RDZ0a0oEfJ0k304VqpJpdrl2ZXa3yFlOxy4mjW7w0="
  [mod."golang.org/x/text"]
    version = "v0.13.0"
    hash = "sha256-J34dbc8UNVIdRJUZP7jPt11oxuwG8VvrOOylxE7V3oA="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20231012201019-e917dd12ba7a"
    hash = "sha256-t7EtLGl9yOIHvkgAK97pMN1agzhcjdpG9zZewsurEnQ="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20231016165738-49dd2c1f3d0b"
    hash = "sha256-V14G5VfWG4zPdTQ+jr3o953vfIhpMnBuF0B4ibsE8ms="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20231016165738-49dd2c1f3d0b"
    hash = "sha256-ntiSoQBTSUfcdkolvYVXWD3BgF+0yur6ZqW+bxtxVlY="
  [mod."google.golang.org/grpc"]
    version = "v1.59.0"
    hash = "sha256-IcwmXyeroUg742wqU4Zikwxm7y0i7x4axOPdWOGPkzE="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."lukechampine.com/blake3"]
    version = "v1.2.1"
    hash = "sha256-x9rHXfq7mAfx8J7ya7uL8tIXhlqDfaRhoFRL66rDVGk="
  [mod."modernc.org/cc/v3"]
    version = "v3.41.0"
    hash = "sha256-D78pkcFaDO2lk1pLdeAld9lfJT4CT9xBMACNiqY5qt0="
  [mod."modernc.org/libc"]
    version = "v1.24.1"
    hash = "sha256-ncVRe3Mx5agBpEoAlEsZkWaVTKulHSZB9DMrWs+iisw="
  [mod."modernc.org/sqlite"]
    version = "v1.26.0"
    hash = "sha256-wpM56GW5IX+oG5IykypDYv4YTxM/oNf7SH10TeG2V70="
