name: gomod2nix.toml up to date

on:
  pull_request:
  push:
    branches: master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: gomod2nix
      run: nix develop -c ./checks/gomod2nix
